spring:
  application:
    name: CampusCalendar

  datasource:
    url: jdbc:mysql://localhost:3307/campus_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user     # docker-compose.yml과 일치
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  flyway:
    enabled: true
    baseline-on-migrate: true

# Swagger UI http://localhost:8080/swagger-ui/index.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs

jwt:
  secret: "v3rys3cr3tk3y_must_be_l0ng_enough_to_be_secure_minimum_256_bits"
  access-expiration-ms: 3600000
  refresh-expiration-ms: 1209600000

# Variable for the crawler
crawler:
  events-json-path: tools/extra-snu-crawler/events.json
